export const options = [
  'Mentor',
  'Mentee',
  'Industry Connection',
  'Hackathon Partner',
];

export const users = [
  {
    email: 'john.doe@example.com',
    password: 'hashed_password_123',
    name: 'John Doe',
    gender: 'Male',
    location: 'Vancouver, Canada',
    hometown: 'Toronto, Canada',
    website: 'johndoe.dev',
    role: 'Software Engineer',
    currentTitle: 'Senior Developer',
    previousTitles: ['Junior Developer', 'Intern'],
    yearsOfExperience: 5,
    currentCompany: 'TechCorp',
    previousCompanies: ['CodeWorks', 'DevSolutions'],
    industries: ['Technology', 'Finance'],
    events: ['Hackathon 2024', 'React Summit'],
    education: [
      {
        school: 'University of British Columbia',
        degree: 'BSc Computer Science',
      },
    ],
    skills: ['JavaScript', 'React', 'Node.js'],
    techStack: ['MongoDB', 'Express', 'React', 'Node'],
    bio: 'Passionate developer focused on building scalable web applications.',
    connectionPreferences: ['Mentorship', 'Networking'],
    learningGoals: ['Master TypeScript', 'Improve system design skills'],
    githubUrl:'thecodersingh',
    linkedinUrl: 'johndoe',
  },
  {
    email: 'jane.smith@example.com',
    password: 'hashed_password_456',
    name: 'Jane Smith',
    gender: 'Female',
    location: 'Seattle, USA',
    hometown: 'Portland, USA',
    website: 'test',
    role: 'Product Manager',
    currentTitle: 'Product Lead',
    previousTitles: ['Product Analyst', 'Junior PM'],
    yearsOfExperience: 7,
    currentCompany: 'Innovatech',
    previousCompanies: ['VisionSoft', 'AgilePro'],
    industries: ['Healthcare', 'Education'],
    events: ['PM Bootcamp', 'Startup Weekend'],
    education: [
      {
        school: 'University of Washington',
        degree: 'MBA',
      },
    ],
    skills: ['Agile Methodology', 'User Research', 'Roadmapping'],
    techStack: ['JIRA', 'Figma'],
    bio: 'Experienced product manager with a track record of successful product launches.',
    connectionPreferences: ['Collaboration', 'Knowledge Sharing'],
    learningGoals: ['Develop data analysis skills', 'Understand AI trends'],
    githubUrl:'thecodersingh',
    linkedinUrl: 'johndoe',
  },
];
